plugins {
    id 'net.fabricmc.fabric-loom' version '1.17.11'
    id 'org.jetbrains.kotlin.jvm' version '2.2.0'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group
base { archivesName = project.archives_base_name }

repositories {
    maven { url 'https://maven.fabricmc.net/' }
    maven { url 'https://maven.terraformersmc.com/releases/' }
    maven { url 'https://maven.shedaniel.me/' }
    maven { url 'https://pkgs.dev.azure.com/djtheredstoner/DevAuth/_packaging/public/maven/v1' }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
    implementation "net.fabricmc:fabric-language-kotlin:${project.fabric_kotlin_version}"

    compileOnly("com.terraformersmc:modmenu:${project.modmenu_version}") {
        exclude(group: "net.fabricmc.fabric-api")
    }

    api("me.shedaniel.cloth:cloth-config-fabric:${project.cloth_version}") {
        exclude(group: "net.fabricmc.fabric-api")
    }

    runtimeOnly "me.djtheredstoner:DevAuth-fabric:1.2.2"
}

loom {
    runs {
        client {
            property "devauth.enabled", "true"
        }
    }
}

processResources {
    inputs.property "version", project.version
    inputs.property "minecraft_version", project.minecraft_version
    duplicatesStrategy = 'EXCLUDE'

    filesMatching("fabric.mod.json") {
        expand "version": project.version,
               "minecraft_version": project.minecraft_version
    }
}

// Ensure resources are copied correctly for IDE builds
sourceSets {
    main {
        resources {
            srcDirs "src/main/resources"
        }
    }
}

tasks.withType(JavaCompile).configureEach { it.options.release = 25 }

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
    compilerOptions.jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_24
}
