org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
minecraft_version=26.2
loader_version=0.19.3
mod_version=1.6.0
maven_group=com.guildzip
archives_base_name=GuildZip
fabric_version=0.153.0+26.2
modmenu_version=19.0.0-alpha.1
cloth_version=26.2.155
fabric_kotlin_version=1.13.4+kotlin.2.2.0
kotlin.jvm.target.validation.mode=warning
