name: Build Mod

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build mod
        run: ./gradlew clean build --stacktrace

      - name: Upload artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: mod-jar
          path: build/libs/*.jar
